USaq\Model\Entity\Token:
  type: entity
  table: tokens
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    tokenString:
      type: string
      column: token_string
    expireAt:
      type: datetime
      column: expire_at
  oneToOne:
    user:
      targetEntity: User
